// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5lOt0UuQwsfZKpMTvLPLzQW1VAH3LfwE',
    appId: '1:448943778156:web:59ca4de98138be95d9eb49',
    messagingSenderId: '448943778156',
    projectId: 'your-d1953',
    authDomain: 'your-d1953.firebaseapp.com',
    storageBucket: 'your-d1953.appspot.com',
    measurementId: 'G-4XRSB6L7JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUnmDSIMHnDk3o2nDKWPggbwN18wxL0Us',
    appId: '1:448943778156:android:edb5e7a6ea2c86f6d9eb49',
    messagingSenderId: '448943778156',
    projectId: 'your-d1953',
    storageBucket: 'your-d1953.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwSoFu0siO9vTLj_0IyEJcpR1NeYy9QjU',
    appId: '1:448943778156:ios:b2a783f14208d39ed9eb49',
    messagingSenderId: '448943778156',
    projectId: 'your-d1953',
    storageBucket: 'your-d1953.appspot.com',
    iosBundleId: 'com.example.your',
  );
}
